version: '3.8'

services:
  api-gateway:
    build: ./ApiGateway
    ports:
      - "5000:80"
    depends_on:
      - user-service
      - product-service

  user-service:
    build: ./UserService
    ports:
      - "5001:80"

  product-service:
    build: ./ProductService
    ports:
      - "5002:80"
